import streamlit as st
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

# Load the Sales data
df = pd.read_csv("Desert.csv")

total = (df["Number of coolers"]).sum()
df['Percentage'] = (df['Number of coolers'] / total) * 100

# Title of the Streamlit app
st.title("Sanghamitra Air Cooler Sales Analysis")
st.write(""" 
This report provides a overview of the cooler sales in the summer of 2022. Through a series of visualizations,
          we aim to illustrate and analyze the sales performance, as well as the revenue generated by our range of coolers. 
""")

#subheading of the dataframe
st.subheader("Price of Cooler Models")


# Pricing data
df_P = pd.read_csv("Pricing.csv")
st.dataframe(df_P.set_index(df_P.columns[0]))

#Bar chart
st.subheader("Sales Percentage of coolers")
fig = px.bar(df, x='Models', y='Percentage')

# Display the chart using Streamlit
st.plotly_chart(fig)

# Time Series data
st.subheader('Weekly Sales Per week')

# Create a time series chart using Plotly Express
dfs = pd.read_csv("Weekly sales.csv")

total_count_s = dfs['Count'].sum()
dfs['Sales Percentage'] = (dfs['Count'] / total_count_s) * 100
fig_T = px.line(dfs, x='Weekly sale', y='Sales Percentage',
                labels={'Count': 'Sales Percentage', 'Weekly sale': 'Weeks of Month'})
# Set Y-axis limits
fig_T.update_yaxes(range=[0, 35])
# Display the chart using Streamlit
st.plotly_chart(fig_T)

# Load the Max sales data
data = pd.read_csv("Max sales.csv")

# Pie chart for Revenue of Coolers
st.subheader("Revenue made by Coolers")
fig_revenue = px.pie(
    data,
    names="Size",
    values="Total",
    labels={"Size": "Cooler Size", "Total": "Revenue"},
)
st.plotly_chart(fig_revenue)
st.subheader("Observation on Revenue Chart:")
st.write("""As the Pie chart shows that from all types of coolers 'Duct 500' generated max revenue which was 82,250 rupees, 
         eventhough people were buying more 'Brio 300'. The second most revenue generated by 'Brio 300' which was 65,950. 
         Followed by 'Brio 450' cooler the revenue generated by it was 41,200 Rupees. The second model of Duct was 'Duct 300' which was second most expensive cooler and the revenue generated by it was 30,800 Rupees. 
         then 10,700 and 7,000 amount were generated by 'Brio 150' and 'Fibre' respectively.""")
