import streamlit as st
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

# Load the Sales data
df = pd.read_csv("Desert.csv")

# Title of the Streamlit app
st.title("Cooler Sales Analysis")
st.write(""" 
This report provides a overview of the cooler sales at Sanghamitra Business Incubator throughout the year 2022. Through a series of visualizations, we aim to illustrate and analyze the sales performance, as well as the revenue generated by our range of coolers. 
         
""")
# Plot bar chart using Matplotlib
st.subheader("Sales of Desert Cooler (Bar Chart)")
colors = ['#009bb3', '#6d4660', '#76483d']
plt.figure(figsize=(10, 6))
plt.bar(df["Desert "], df["Number of coolers"], color=colors)
plt.title("Count of Desert Cooler")
plt.xlabel("Desert Model")
plt.ylabel("Count")
plt.xticks(rotation=45, ha='right')  # Adjust rotation for better visibility
st.pyplot(plt.gcf())
st.subheader("Observation on Bar Chart:")
st.write("""In Desert Coolers the 3.5 feet desert was the best seller with sales of 10 coolers, 
         then six '4 feet' desert were sold and three 2.5 feet desert cooler.""")
st.subheader("")


df2 = pd.read_csv("Duct.csv")
# Filter and plot Duct Cooler counts as bar chart
# Plot bar chart using Matplotlib
st.subheader("Sales of Duct Cooler (Bar Chart)")
plt.figure(figsize=(10, 6))
plt.bar(df2["Duct"], df2["Number of coolers"], color=colors)
plt.title("Count of Duct Cooler")
plt.xlabel("Duct Model")
plt.ylabel("Count")
plt.xticks(rotation=45, ha='right')  # Adjust rotation for better visibility
st.pyplot(plt.gcf())

st.subheader("Observation on Bar charts")
st.write("""The duct cooler the best seller was Duct 500 with six coolers were sold and 3 duct 300 were sold.""")
st.subheader("")

# Load the Max sales data
data = pd.read_csv("Max sales.csv")

# Pie chart for Revenue of Coolers
st.subheader("Revenue made by Coolers")
fig_revenue = px.pie(
    data,
    names="Size",
    values="Total",
    labels={"Size": "Cooler Size", "Total": "Revenue"},
)
st.plotly_chart(fig_revenue)
st.subheader("Observation on Revenue Chart:")
st.write("""As the Pie chart shows that from all types of coolers Duct 500 generated max revenue which was 82,250 rupees, 
         eventhough people were buying more 3.5 feet desert coolers. The second most revenue generated by 3.5 feet desert cooler which was 65,950. 
         Followed by '4 feet desert' cooler the revenue generated by it was 41,200 Rupees. The second model of Duct was 'Duct 300' which was second most expensive cooler and the revenue generated by it was 30,800 Rupees. 
         then 10,700 and 7,000 amount were generated by '2.5 feet Desert' and 'Fibre' respectively."""),
