import streamlit as st
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

# Load the Sales data
df = pd.read_csv("Desert.csv")

total = (df["Number of coolers"]).sum()
df['Percentage'] = (df['Number of coolers'] / total) * 100

# Title of the Streamlit app
st.title("Sanghamitra Air Cooler Sales Dashboard")
st.write(""" 
This report offers an overview of cooler sales during the summer of 2022. Through 
         visualizations, our goal is to illustrate and analyze sales performance and 
         the revenue generated by our range of coolers. The objective of this analysis 
         is to gain insights into sales trends, enabling us to predict future sales and 
         make crucial decisions regarding raw material orders, inventory management, and 
         business investments. The information presented in these visualizations provides 
         insights into the best and least selling products, aiding in overall business
          process management and effective decision-making. 
""")

#subheading of the dataframe
st.subheader("Price of Cooler Models")


# Pricing data
df_P = pd.read_csv("Pricing.csv")
st.dataframe(df_P.set_index(df_P.columns[0]))
st.write("""The table below represents the prices of cooler models, varying based on size,
          motor type, materials, and tank capacity. The costliest product, 'Duct 500', and
          the least expensive, 'Brio 250', differ in features. Pricing decisions were 
         informed by extensive market research and the production costs associated with
          each model. Determining economically viable yet premium prices posed a 
         challenge, but we successfully brought competitive products to market.""")

#Bar chart
st.subheader("Sales Percentage of coolers")
fig = px.bar(df, x='Models', y='Percentage')

# Display the chart using Streamlit
st.plotly_chart(fig)

# Observations
st.subheader("Observations on Sales Percentage")
st.write("""Our major audience, largely comprising the middle class, favored the 
         "Brio 300" due to its affordability and superior quality. It emerged as our 
         most popular product, followed by "Brio 450" and "Duct 500." We effectively 
         met market demands and competed with established businesses to capture a 
         significant share.""")

# Time Series data
st.subheader('Cooler Sales Per week')

# Create a time series chart using Plotly Express
dfs = pd.read_csv("Weekly sales.csv")

total_count_s = dfs['Count'].sum()
dfs['Sales Percentage'] = (dfs['Count'] / total_count_s) * 100
fig_T = px.line(dfs, x='Weekly sale', y='Sales Percentage',
                labels={'Count': 'Sales Percentage', 'Weekly sale': 'Weeks of Month'})
# Set Y-axis limits
fig_T.update_yaxes(range=[0, 35])
# Display the chart using Streamlit
st.plotly_chart(fig_T)
st.subheader("Observations of Weekly Sales:")
st.write("""Weekly sales exhibited fluctuations, with a slow start as customers did not
          immediately require coolers at the beginning of summer. Sales gained momentum 
         as temperatures rose, reaching peak levels from mid-March to early April. During 
         this period, the demand for cooling solutions was at its highest due to extreme temperatures.""")
# Load the Max sales data
data = pd.read_csv("Max sales.csv")

# Pie chart for Revenue of Coolers
st.subheader("Revenue made by Coolers")
fig_revenue = px.pie(
    data,
    names="Size",
    values="Total",
    labels={"Size": "Cooler Size", "Total": "Revenue"},
)
st.plotly_chart(fig_revenue)
st.subheader("Observations on Revenue:")
st.write("""The pie chart illustrates that, despite "Brio 300" being the highest-selling
          model, "Duct 500" generated the maximum revenue of 34.6%. "Brio 300"
          followed closely with revenue of 27.7%, and "Brio 450" generated 17.3%. 
         The second Duct model, "Duct 300," the second most expensive cooler, 
         contributed 12.9% to the revenue. "Brio 150" and "Fibre" generated revenue of 4.5% and 2.94%, respectively.
""")

st.subheader("Conclusion")
st.write("""The analysis has informed crucial decisions for the upcoming year's business
          processes. Based on the findings, we have adjusted our production quantities, 
         prioritizing the most popular product, "Brio 300." Additionally, we have increased
         production for "Brio 450" and "Duct 500," recognizing their popularity. This 
         strategic approach allows us to focus resources on meeting market demand efficiently. """)
